### ISSUE TITLE
Ubuntu MATE arm7 Rpi

### ISSUE THREAD

**Issue by Ktysai** [dheera/rosshow#15]
Hello,

Quite a nice package! I would be veeery nice to extract the info from Win10 through Putty.

Help a little bit a n00b in Ros and Linux.

1 -  installation on Ros binaries din not worked, maybe there were some hidden steps?
2 - on a simple ros package installation, I get 
**Topic raspicam_node/camera_info does not appear to be published yet.**

Cheers!

**Comment by dheera** [comment]
Hi @Ktysai -- I'm reading this as an issue with installing ros and the raspberry pi camera node and not rosshow. If that's true, you might want to ask this question either in the
- ROS discourse forums https://discourse.ros.org
- Ubiquity Robotics forum https://forum.ubiquityrobotics.com/
- Raspberry Pi forums https:/lwww.raspberrypi.org/forums/

I'm closing this issue here for now. If your issue is in fact specific to rosshow please feel free to re-open it and clarify your question. Thanks!
